server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  #consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        heartbeat:
          #必须加，心跳检测
          enabled: true
        #去找哪个服务名称
        service-name: ${spring.application.name}
