server:
  port: 80

eureka:
  client:
    #表示是否将自己注册进EurekaServer，默认为true;如果不想注册进Eureka，就写false
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbo使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群

#设置feign客户端超时时间(OpenFeign默认支持Ribbon)
ribbon:
  #指的是建立连接所用时间，适用于网络正常情况下，两端连接所用的时间
  ConnectTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间，默认1秒，这里设置5秒
  ReadTimeout: 5000
logging:
  level:
    com.wangwren.springcloud.service.PaymentFeignService: debug

